sudo: required

services:
  - docker

before_install:
  - docker build -t devenzo/docker-react -f Dockerfile.dev . 

script:
  - docker run -e CI=true devenzo/docker-react npm run test -- --coverage
  
language: generic